[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "pesten"
version = "0.0.1"
requires-python = ">=3.8"
keywords = ["one", "two"]
dependencies = [
    "fastapi",
    "uvicorn",
    "websockets",
    "httpx",
]
